#!/bin/sh
# Write azd outputs to a local .env file after `azd provision`
set -e

echo "Writing environment variables to .env ..."

MCP_SERVER_URL=$(azd env get-values | grep MCP_SERVER_URL | cut -d= -f2 | tr -d '"')
APPINSIGHTS=$(azd env get-values | grep APPLICATIONINSIGHTS_CONNECTION_STRING | cut -d= -f2- | tr -d '"')

cat > .env <<EOF
# Auto-generated by infra/write_env.sh after azd provision
# Edit the values below for services provisioned outside azd

MCP_SERVER_URL=${MCP_SERVER_URL}
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPINSIGHTS}

# Set these to point to your Azure AI Foundry project and Azure OpenAI resource
AZURE_AI_PROJECT_ENDPOINT=
AZURE_AI_SEARCH_ENDPOINT=
AZURE_AI_SEARCH_INDEX_NAME=project-log-index
AZURE_OPENAI_ENDPOINT=
AZURE_OPENAI_EMBEDDING_MODEL=text-embedding-3-small
AZURE_OPENAI_EMBEDDING_DIMENSIONS=1536
AZURE_OPENAI_COMPLETION_MODEL_NAME=
EOF

echo "Done. Review .env and fill in any missing values."
