#!/bin/sh
# Write azd provision outputs to a local .env file
set -e

echo "Writing environment variables to .env ..."

get_val() { azd env get-values 2>/dev/null | grep "^$1=" | cut -d= -f2- | tr -d '"'; }

MCP_SERVER_URL=$(get_val MCP_SERVER_URL)
APPINSIGHTS=$(get_val APPLICATIONINSIGHTS_CONNECTION_STRING)
AI_PROJECT_ENDPOINT=$(get_val AZURE_AI_PROJECT_ENDPOINT)
OPENAI_ENDPOINT=$(get_val AZURE_OPENAI_ENDPOINT)
COMPLETION_MODEL=$(get_val AZURE_OPENAI_COMPLETION_MODEL_NAME)
EMBEDDING_MODEL=$(get_val AZURE_OPENAI_EMBEDDING_MODEL)
SEARCH_ENDPOINT=$(get_val AZURE_AI_SEARCH_ENDPOINT)
SEARCH_INDEX=$(get_val AZURE_AI_SEARCH_INDEX_NAME)
ACR_NAME=$(get_val AZURE_CONTAINER_REGISTRY_NAME)
RESOURCE_GROUP=$(get_val AZURE_RESOURCE_GROUP)

cat > .env <<ENVEOF
# Auto-generated by infra/write_env.sh after azd provision
# Re-run 'azd provision' to refresh these values

MCP_SERVER_URL=${MCP_SERVER_URL}

# Azure AI Foundry
AZURE_AI_PROJECT_ENDPOINT=${AI_PROJECT_ENDPOINT}
AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_COMPLETION_MODEL_NAME=${COMPLETION_MODEL}
AZURE_OPENAI_EMBEDDING_MODEL=${EMBEDDING_MODEL}
AZURE_OPENAI_EMBEDDING_DIMENSIONS=1536

# Azure AI Search
AZURE_AI_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
AZURE_AI_SEARCH_INDEX_NAME=${SEARCH_INDEX}

# Monitoring
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPINSIGHTS}

# Infrastructure
AZURE_CONTAINER_REGISTRY_NAME=${ACR_NAME}
AZURE_RESOURCE_GROUP=${RESOURCE_GROUP}

# Local transport (stdio for uvx / VS Code, http for testing the container locally)
TRANSPORT=stdio
RUNNING_IN_PRODUCTION=false
ENVEOF

echo "Done. .env written. Run 'az login' to authenticate for local development."
